### ISSUE TITLE
loading textures from the filesystem

### ISSUE THREAD

**Issue by mreinstein** [kmamal/gpu#2]
It's fairly easy to load textures from a URL via the browser's built in `createImageBitmap` function:

```javascript
const response = await fetch('https://foo.com/bar.png')
const blob = await response.blob()

const imageData = await createImageBitmap(blob/*, { premultiplyAlpha: 'none', resizeQuality: 'pixelated' }*/)

const texture = device.createTexture({
    label,
    size: { width: imageData.width, height: imageData.height },
    format,
    usage:  GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST | GPUTextureUsage.RENDER_ATTACHMENT,
    mipLevelCount: 1,
    sampleCount: 1,
    dimension: '2d',
})

device.queue.copyExternalImageToTexture(
    { source: imageData },
    { texture },
    {
      width: imageData.width,
      height: imageData.height
    }
)
```

How does one do this in `kmamal/gpu` ?

**Comment by mreinstein** [comment]
@kmamal blocking my testing/eval as per https://github.com/kmamal/node-sdl/issues/20#issuecomment-1806434024

**Comment by kmamal** [comment]
I'll see what I can do.

For a first round of testing it should be enough to run the [readme example](https://github.com/kmamal/node-sdl#webgpu) and see if there's any crashes and if the  window does show red

**Comment by mreinstein** [comment]
I get a segmentation fault when I attempt to run the readme webgpu example on macos.  Will try windows 11 now.

**Comment by kmamal** [comment]
Is it an intel or arm machne?

**Comment by mreinstein** [comment]
<img width="278" alt="Screenshot 2023-11-15 at 12 09 12 PM" src="https://github.com/kmamal/gpu/assets/718067/a7e02008-c8cd-4a2a-a9db-8c86cdd15b51">

**Comment by mreinstein** [comment]
Here's what I get in windows:

```bash
Node.js v20.7.0
PS C:\Users\Michael\projects\test-sdl> node main.js
Error: DXC create compiler failed with <Unknown HRESULT> (0x80004002)
    at CheckHRESULTImpl (D:\a\gpu\gpu\dawn\src\dawn\native\d3d\D3DError.cpp:111)
    at EnsureDxcCompiler (D:\a\gpu\gpu\dawn\src\dawn\native\d3d\BackendD3D.cpp:143)
    at operator () (D:\a\gpu\gpu\dawn\src\dawn\native\d3d\BackendD3D.cpp:179)
```

**Comment by kmamal** [comment]
Thanks for the tests! I'll try to reproduce them somehow. Maybe spin up a few VMs and see if that does it. I'll be posting my progress in the original ticket.

---
On to this ticket's main subject: I'm afraid that `copyExternalImageToTexture` is unimplemented in the node.js bindings: https://github.com/google/dawn/blob/main/src/dawn/node/binding/GPUQueue.cpp#L156-L161

This makes sense since there are no well-established Image classes in the node.js ecosystem. I have also avoided creating my own Image class for this set of libararies - to let people use whatever image decoding library they prefer.

You will have to use a library of your choice to convert the loaded image to an array of RGB values, and then you can write it to the texture using [device.queue.writeTexture()](https://developer.mozilla.org/en-US/docs/Web/API/GPUQueue/writeTexture#examples)

**Comment by mreinstein** [comment]
> You will have to use a library of your choice to convert the loaded image to an array of RGB values, and then you can write it to the texture using [device.queue.writeTexture()](https://developer.mozilla.org/en-US/docs/Web/API/GPUQueue/writeTexture#examples)

Alright if I manage to figure that out I'll send a PR with my steps.

**Comment by kmamal** [comment]
No PR necessary. I don't plan to include that functionality to keep things agnostic of what decoding library is being used.

**Comment by mreinstein** [comment]
>  to keep things agnostic of what decoding library is being used

I get that, but from a practical standpoint, I suspect that the majority of users of webgpu will want to load textures in some way, and most won't know how. :)

**Comment by kmamal** [comment]
Yeah that's a good point... I'll add this as an example so there's some ready to use code people can just copy and paste.

**Comment by mreinstein** [comment]
I can poke at it a bit, I don't want to overload you with requests.  I suspect it's probably pretty straightforward, reading some file as a binary and specificying it's rgba encoding in some way.

**Comment by kmamal** [comment]
Example added: https://github.com/kmamal/gpu/tree/master/examples

**Comment by mreinstein** [comment]
You're on 🔥  today!
